# -*- coding: utf-8 -*-
"""Centrally_Nucleated_Fiber_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QaFBK0036sOZD8DabIy8ZZ_FcI-e_81h
"""

"""
Centrally Nucleated Fiber Quantification
-----------------------------------------
Statistics: Kruskal-Wallis + Dunn's post-hoc + Bonferroni correction
Unit of analysis: individual fibers (Classify_CNF = 0 or 1)

Input:  ShrunkMuscle.csv from the CellProfiler Centrally Nucleated Fiber pipeline
Output: cnf_kw_raw.png/.pdf
        cnf_kw_bonf.png/.pdf
"""

import pandas as pd
import numpy as np
import matplotlib
matplotlib.use("Agg")
matplotlib.rcParams["pdf.fonttype"] = 42
matplotlib.rcParams["ps.fonttype"]  = 42
import matplotlib.pyplot as plt
from scipy.stats import kruskal, norm as scipy_norm
from itertools import combinations

# ══════════════════════════════════════════════════════════════════════════════
# USER SETTINGS
# ══════════════════════════════════════════════════════════════════════════════

CNF_FILE = "ShrunkMuscle.csv"

TREATMENT_MAP = {
    "Uninjured":       "Uninjured",
    "Uninjured+Ibu":   "Uninjured + Ibuprofen",
    "Uninjured+Ibu+C": "Uninjured + Ibu + Carnitine",
    "SBI":             "SBI",
    "SBI+Ibu":         "SBI + Ibuprofen",
    "SBI+Ibu+C":       "SBI + Ibu + Carnitine",
}

TREATMENT_ORDER = [
    "Uninjured",
    "Uninjured + Ibuprofen",
    "Uninjured + Ibu + Carnitine",
    "SBI",
    "SBI + Ibuprofen",
    "SBI + Ibu + Carnitine",
]

DOT_COLORS = {
    "Uninjured":                   "#888780",
    "Uninjured + Ibuprofen":       "#6B4FA0",
    "Uninjured + Ibu + Carnitine": "#D85A30",
    "SBI":                         "#888780",
    "SBI + Ibuprofen":             "#6B4FA0",
    "SBI + Ibu + Carnitine":       "#D85A30",
}

BG_SBI   = "#E8E0F5"
BG_UNINJ = "#FDF8E1"

XAXIS_IBUPROFEN = ["-", "+", "+", "-", "+", "+"]
XAXIS_CARNITINE = ["-", "-", "+", "-", "-", "+"]

LOG10_005 = np.log10(0.05)  # significance threshold = -1.301

# Pairs to show brackets for (only if significant after Bonferroni)
# 1=Uninjured, 2=Uninj+Ibu, 3=Uninj+Ibu+C, 4=SBI, 5=SBI+Ibu, 6=SBI+Ibu+C
PAIRS_TO_SHOW = {
    tuple(sorted([TREATMENT_ORDER[0], TREATMENT_ORDER[1]])),  # 1-2
    tuple(sorted([TREATMENT_ORDER[0], TREATMENT_ORDER[2]])),  # 1-3
    tuple(sorted([TREATMENT_ORDER[1], TREATMENT_ORDER[2]])),  # 2-3
    tuple(sorted([TREATMENT_ORDER[3], TREATMENT_ORDER[4]])),  # 4-5
    tuple(sorted([TREATMENT_ORDER[3], TREATMENT_ORDER[5]])),  # 4-6
    tuple(sorted([TREATMENT_ORDER[4], TREATMENT_ORDER[5]])),  # 5-6
    tuple(sorted([TREATMENT_ORDER[0], TREATMENT_ORDER[3]])),  # 1-4
    tuple(sorted([TREATMENT_ORDER[1], TREATMENT_ORDER[4]])),  # 2-5
    tuple(sorted([TREATMENT_ORDER[2], TREATMENT_ORDER[5]])),  # 3-6
}

# ══════════════════════════════════════════════════════════════════════════════
# HELPER FUNCTIONS
# ══════════════════════════════════════════════════════════════════════════════

def fmt_pval(log10p):
    """Format p-value stored as log10(p) — exact even for p~10^-100."""
    if pd.isna(log10p):
        return "p=NA"
    exponent = int(np.floor(log10p))
    mantissa = 10 ** (log10p - exponent)
    return f"p={mantissa:.2f}x10^{exponent}"


def draw_bracket(ax, x1, x2, y, label, y_data_max):
    h = y_data_max * 0.012
    ax.plot([x1, x1, x2, x2], [y, y + h, y + h, y],
            color="black", linewidth=1.2)
    ax.text((x1 + x2) / 2, y + h, label,
            ha="center", va="bottom", fontsize=7.5)


def add_brackets(ax, pval_dict, y_data_max):
    """Draw brackets only for PAIRS_TO_SHOW that are significant."""
    idx = {t: i for i, t in enumerate(TREATMENT_ORDER)}
    seen = set()
    sig_pairs = []
    for (g1, g2), lp in pval_dict.items():
        key = tuple(sorted([g1, g2]))
        if key in seen:
            continue
        seen.add(key)
        if key in PAIRS_TO_SHOW and not pd.isna(lp) and lp < LOG10_005:
            sig_pairs.append((key[0], key[1], lp))
    sig_pairs.sort(key=lambda c: abs(idx[c[1]] - idx[c[0]]))
    y_start = y_data_max * 1.15
    y_step  = y_data_max * 0.14
    for i, (g1, g2, lp) in enumerate(sig_pairs):
        draw_bracket(ax, idx[g1], idx[g2],
                     y_start + i * y_step, fmt_pval(lp), y_data_max)


def y_max_for(pval_dict, y_data_max):
    seen = set()
    n_sig = 0
    for (g1, g2), lp in pval_dict.items():
        key = tuple(sorted([g1, g2]))
        if key in seen:
            continue
        seen.add(key)
        if key in PAIRS_TO_SHOW and not pd.isna(lp) and lp < LOG10_005:
            n_sig += 1
    return y_data_max * 1.15 + max(n_sig, 1) * y_data_max * 0.14 + y_data_max * 0.15


def set_xaxis_labels(ax):
    ax.set_xticks(np.arange(len(TREATMENT_ORDER)))
    ax.set_xticklabels([])
    for row_idx, (row_label, row_vals) in enumerate(
            zip(["Ibuprofen", "Carnitine"], [XAXIS_IBUPROFEN, XAXIS_CARNITINE])):
        y_ax = -0.09 - row_idx * 0.075
        ax.text(-0.5, y_ax, row_label, transform=ax.get_xaxis_transform(),
                ha="right", va="center", fontsize=9, style="italic", color="#333333")
        for col_idx, val in enumerate(row_vals):
            ax.text(col_idx, y_ax, val, transform=ax.get_xaxis_transform(),
                    ha="center", va="center", fontsize=10, color="black",
                    fontweight="bold" if val == "+" else "normal")
    ax.axhline(y=0, color="black", linewidth=0.5, clip_on=False)
    ax.text(1.0, -0.27, "Uninjured", transform=ax.get_xaxis_transform(),
            ha="center", va="top", fontsize=10, color="#6B4FA0", fontweight="bold")
    ax.text(4.0, -0.27, "SBI (injured)", transform=ax.get_xaxis_transform(),
            ha="center", va="top", fontsize=10, color="#6B4FA0", fontweight="bold")


# ══════════════════════════════════════════════════════════════════════════════
# 1. LOAD DATA
# ══════════════════════════════════════════════════════════════════════════════

print("Loading CNF data...")
cnf_raw = pd.read_csv(CNF_FILE)

cnf_raw = cnf_raw.rename(columns={
    "Metadata_Sample":     "mouse_ID",
    "Metadata_Group":      "treatment_abbrev",
    "Metadata_ROI_number": "image_number",
})

cnf_raw["group"] = cnf_raw["treatment_abbrev"].map(TREATMENT_MAP)

unmapped = cnf_raw["group"].isna().sum()
if unmapped:
    print(f"Warning: {unmapped} rows had unrecognised treatment abbreviations and will be dropped.")
    print(cnf_raw.loc[cnf_raw["group"].isna(), "treatment_abbrev"].unique())

fibers = cnf_raw.dropna(subset=["group"]).copy()
print(f"Loaded {len(fibers):,} fibers across {fibers['mouse_ID'].nunique()} mice.")

print("\nPer-mouse fiber counts and CNF rates:")
summary = (fibers.groupby(["mouse_ID", "group"])["Classify_CNF"]
           .agg(total="count", n_cnf="sum")
           .assign(pct_CNF=lambda d: 100 * d["n_cnf"] / d["total"])
           .reset_index())
print(summary.sort_values(["group", "mouse_ID"]).to_string(index=False))

# Per-mouse CNF % for dot overlay on figure
per_mouse = summary[["mouse_ID", "group", "pct_CNF"]].copy()

# ══════════════════════════════════════════════════════════════════════════════
# 2. KRUSKAL-WALLIS OMNIBUS TEST (per individual fiber, Classify_CNF = 0 or 1)
# ══════════════════════════════════════════════════════════════════════════════

fiber_arrays = [fibers.loc[fibers["group"] == t, "Classify_CNF"].values
                for t in TREATMENT_ORDER]

kw_stat, kw_p = kruskal(*fiber_arrays)
print(f"\nKruskal-Wallis (per-fiber CNF 0/1, n={len(fibers):,}): H = {kw_stat:.3f}, p = {kw_p:.4e}")

# ══════════════════════════════════════════════════════════════════════════════
# 3. DUNN'S POST-HOC
#    p-values stored as log10(p) throughout to avoid underflow
# ══════════════════════════════════════════════════════════════════════════════

all_vals   = fibers["Classify_CNF"].values.astype(float)
all_groups = fibers["group"].values

ranks   = pd.Series(all_vals).rank(method="average").values
n_total = len(ranks)

_, tie_counts  = np.unique(all_vals, return_counts=True)
tie_correction = np.sum(tie_counts**3 - tie_counts) / (12 * (n_total - 1))

rows = []
for g1, g2 in combinations(TREATMENT_ORDER, 2):
    mask1 = all_groups == g1
    mask2 = all_groups == g2
    n1, n2 = mask1.sum(), mask2.sum()
    r1, r2 = ranks[mask1].mean(), ranks[mask2].mean()
    se     = np.sqrt((n_total * (n_total + 1) / 12 - tie_correction) * (1/n1 + 1/n2))
    z_stat = (r1 - r2) / se
    log10_p_raw = (np.log(2) + scipy_norm.logsf(abs(z_stat))) / np.log(10)
    rows.append({"group1": g1, "group2": g2, "z": z_stat, "log10_p_raw": log10_p_raw})

dunn_df = pd.DataFrame(rows)
n_pairs = len(dunn_df)

# Bonferroni on log scale
dunn_df["log10_p_bonf"] = np.minimum(
    dunn_df["log10_p_raw"] + np.log10(n_pairs), 0.0)

dunn_df = dunn_df.sort_values("log10_p_raw").reset_index(drop=True)

print(f"\nDunn's post-hoc ({n_pairs} pairs), sorted by p:")
print(f"  {'Group 1':<35} {'Group 2':<35} {'z':>8}  {'raw p':>18}  {'Bonf p':>18}")
print(f"  {'-'*35} {'-'*35} {'-'*8}  {'-'*18}  {'-'*18}")
for _, row in dunn_df.iterrows():
    print(f"  {row['group1']:<35} {row['group2']:<35} "
          f"{row['z']:+8.3f}  "
          f"{fmt_pval(row['log10_p_raw']):>18}  "
          f"{fmt_pval(row['log10_p_bonf']):>18}")

# Build lookup dicts (log10 p)
dunn_pvals_raw  = {}
dunn_pvals_bonf = {}
for _, row in dunn_df.iterrows():
    key = (row["group1"], row["group2"])
    rev = (row["group2"], row["group1"])
    dunn_pvals_raw[key]  = dunn_pvals_raw[rev]  = row["log10_p_raw"]
    dunn_pvals_bonf[key] = dunn_pvals_bonf[rev] = row["log10_p_bonf"]

print("\nSignificant pairs — raw p-values:")
for (g1, g2), lp in sorted(dunn_pvals_raw.items()):
    if g1 < g2 and lp < LOG10_005:
        print(f"  {g1} vs {g2}: {fmt_pval(lp)}")

print("\nSignificant pairs — Bonferroni-adjusted p-values:")
found = False
for (g1, g2), lp in sorted(dunn_pvals_bonf.items()):
    if g1 < g2 and lp < LOG10_005:
        print(f"  {g1} vs {g2}: {fmt_pval(lp)}")
        found = True
if not found:
    print("  None")

# ══════════════════════════════════════════════════════════════════════════════
# 4. DRAW AND SAVE FIGURES
# ══════════════════════════════════════════════════════════════════════════════

def draw_bars(ax, pval_dict, title):
    group_stats = (per_mouse.groupby("group")["pct_CNF"]
                   .agg(mean="mean", se=lambda x: x.std() / np.sqrt(len(x)))
                   .reindex(TREATMENT_ORDER))

    positions  = np.arange(len(TREATMENT_ORDER))
    rng        = np.random.default_rng(42)
    y_data_max = per_mouse["pct_CNF"].max()
    Y_MAX      = y_max_for(pval_dict, y_data_max)

    ax.axvspan(-0.5, 2.5, color=BG_UNINJ, zorder=0)
    ax.axvspan(2.5,  5.5, color=BG_SBI,   zorder=0)

    for i, t in enumerate(TREATMENT_ORDER):
        if t not in group_stats.index or pd.isna(group_stats.loc[t, "mean"]):
            continue
        ax.bar(i, group_stats.loc[t, "mean"],
               color=DOT_COLORS[t], alpha=0.75, width=0.6,
               edgecolor="white", linewidth=0.5, zorder=2)
        ax.errorbar(i, group_stats.loc[t, "mean"],
                    yerr=group_stats.loc[t, "se"],
                    fmt="none", color="black", linewidth=1.5, capsize=4, zorder=3)

    # Per-mouse CNF % dots
    for i, t in enumerate(TREATMENT_ORDER):
        vals = per_mouse.loc[per_mouse["group"] == t, "pct_CNF"].values
        jit  = rng.uniform(-0.12, 0.12, size=len(vals))
        ax.scatter(positions[i] + jit, vals,
                   s=55, color="white", edgecolors="black",
                   linewidths=1.3, zorder=5)

    add_brackets(ax, pval_dict, y_data_max)
    set_xaxis_labels(ax)

    ax.set_ylabel("% Centrally Nucleated Fibers", fontsize=11)
    ax.set_xlim(-0.5, 5.5)
    ax.set_ylim(0, Y_MAX)
    ax.spines[["top", "right", "bottom"]].set_visible(False)
    ax.tick_params(axis="x", length=0)
    ax.set_title(title, fontsize=10, pad=8)


outputs = [
    ("cnf_kw_raw",  dunn_pvals_raw,
     f"CNF % — Kruskal-Wallis + Dunn's, raw p-values\n(H={kw_stat:.2f}, p={kw_p:.2e})",
     "png"),
    ("cnf_kw_raw",  dunn_pvals_raw,
     f"CNF % — Kruskal-Wallis + Dunn's, raw p-values\n(H={kw_stat:.2f}, p={kw_p:.2e})",
     "pdf"),
    ("cnf_kw_bonf", dunn_pvals_bonf,
     f"CNF % — Kruskal-Wallis + Dunn's, Bonferroni-adjusted p-values (n={n_pairs})\n"
     f"(H={kw_stat:.2f}, p={kw_p:.2e})",
     "png"),
    ("cnf_kw_bonf", dunn_pvals_bonf,
     f"CNF % — Kruskal-Wallis + Dunn's, Bonferroni-adjusted p-values (n={n_pairs})\n"
     f"(H={kw_stat:.2f}, p={kw_p:.2e})",
     "pdf"),
]

for stem, pval_dict, title, fmt in outputs:
    fig, ax = plt.subplots(figsize=(10, 7))
    fig.subplots_adjust(bottom=0.22)
    draw_bars(ax, pval_dict, title)
    fname = f"{stem}.{fmt}"
    save_kwargs = {"format": fmt, "bbox_inches": "tight"}
    if fmt == "png":
        save_kwargs["dpi"] = 300
    fig.savefig(fname, **save_kwargs)
    plt.close(fig)
    print(f"Saved {fname}")

print("\nAll done.")