# -*- coding: utf-8 -*-
"""cross_sectional_area_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GJVzY9hbxMxeo9Mjhm3SWRC55PO9aG6o
"""

"""
Cross-sectional area analysis
Kruskal-Wallis + Dunn's post-hoc (individual fibers)
Input:  qupath_CSA_analysis.csv from QuPath cross-sectional area pipeline
Output: fig_violin_kw_raw.png/.pdf
        fig_violin_kw_bonf.png/.pdf
"""

import pandas as pd
import numpy as np
import re
import matplotlib
matplotlib.rcParams["pdf.fonttype"] = 42
matplotlib.rcParams["ps.fonttype"]  = 42
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.lines import Line2D
from scipy.stats import kruskal, norm as scipy_norm
from itertools import combinations

# ══════════════════════════════════════════════════════════════════════════════
# USER SETTINGS
# ══════════════════════════════════════════════════════════════════════════════

INPUT_FILE = "qupath_CSA_analysis.csv"

TREATMENT_MAP = {
    "Uninjured":         "Uninjured",
    "Uninjured+Ibu":     "Uninjured + Ibuprofen",
    "Uninjured+Ibu+C":   "Uninjured + Ibu + Carnitine",
    "SBI":               "SBI",
    "SBI+Ibu":           "SBI + Ibuprofen",
    "SBI+Ibu+C":         "SBI + Ibu + Carnitine",
    "Uninj+Ibup":        "Uninjured + Ibuprofen",
    "Uninj+Ibup+Car":    "Uninjured + Ibu + Carnitine",
    "SBI+Ibuprofen":     "SBI + Ibuprofen",
    "SBI+Ibu+Car":       "SBI + Ibu + Carnitine",
}

TREATMENT_ORDER = [
    "Uninjured",
    "Uninjured + Ibuprofen",
    "Uninjured + Ibu + Carnitine",
    "SBI",
    "SBI + Ibuprofen",
    "SBI + Ibu + Carnitine",
]

RANDOM_SEED = 42
LOG10_005   = np.log10(0.05)   # significance threshold on log10 scale = -1.301

DOT_COLORS = {
    "Uninjured":                   "#888780",
    "Uninjured + Ibuprofen":       "#6B4FA0",
    "Uninjured + Ibu + Carnitine": "#D85A30",
    "SBI":                         "#888780",
    "SBI + Ibuprofen":             "#6B4FA0",
    "SBI + Ibu + Carnitine":       "#D85A30",
}
BG_SBI   = "#E8E0F5"
BG_UNINJ = "#FDF8E1"

XAXIS_IBUPROFEN = ["-", "+", "+", "-", "+", "+"]
XAXIS_CARNITINE = ["-", "-", "+", "-", "-", "+"]

BIN_EDGES  = [0, 250, 500, 750, 1000, 1500, 2000, 3000, np.inf]
BIN_LABELS = ["0-250", "250-500", "500-750", "750-1k",
              "1-1.5k", "1.5-2k", "2-3k", "3k+"]
BIN_COLORS = [
    "#F7FCF5", "#C7E9C0", "#A1D99B", "#74C476",
    "#41AB5D", "#238B45", "#006D2C", "#00441B",
]

# ══════════════════════════════════════════════════════════════════════════════
# HELPER FUNCTIONS
# ══════════════════════════════════════════════════════════════════════════════

def parse_image_filename(img):
    stem = img.split(" - ")[0].strip()
    stem = re.sub(r"\.tif.*$", "", stem, flags=re.IGNORECASE)
    parts = stem.split("_")
    if len(parts) < 4:
        return None, None, None
    return parts[1], parts[0], parts[3]


def fmt_pval(log10p):
    """
    Format a p-value stored as log10(p).
    Works correctly even for p ~ 10^-100 that would underflow to 0.0.
    """
    if pd.isna(log10p):
        return "p=NA"
    exponent = int(np.floor(log10p))
    mantissa = 10 ** (log10p - exponent)
    return f"p={mantissa:.2f}x10^{exponent}"


def draw_bracket(ax, x1, x2, y, label, y_data_max):
    h = y_data_max * 0.018
    ax.plot([x1, x1, x2, x2], [y, y + h, y + h, y],
            color="black", lw=1.2, clip_on=False, zorder=6)
    ax.text((x1 + x2) / 2, y + h * 1.8, label,
            ha="center", va="bottom", fontsize=9, zorder=6)


# Pairs to show brackets for (1=Uninjured, 2=Uninj+Ibu, 3=Uninj+Ibu+C,
#                              4=SBI,       5=SBI+Ibu,   6=SBI+Ibu+C)
PAIRS_TO_SHOW = {
    tuple(sorted([TREATMENT_ORDER[0], TREATMENT_ORDER[1]])),  # 1-2
    tuple(sorted([TREATMENT_ORDER[0], TREATMENT_ORDER[2]])),  # 1-3
    tuple(sorted([TREATMENT_ORDER[1], TREATMENT_ORDER[2]])),  # 2-3
    tuple(sorted([TREATMENT_ORDER[3], TREATMENT_ORDER[4]])),  # 4-5
    tuple(sorted([TREATMENT_ORDER[3], TREATMENT_ORDER[5]])),  # 4-6
    tuple(sorted([TREATMENT_ORDER[4], TREATMENT_ORDER[5]])),  # 5-6
    tuple(sorted([TREATMENT_ORDER[0], TREATMENT_ORDER[3]])),  # 1-4
    tuple(sorted([TREATMENT_ORDER[1], TREATMENT_ORDER[4]])),  # 2-5
    tuple(sorted([TREATMENT_ORDER[2], TREATMENT_ORDER[5]])),  # 3-6
}

def add_brackets(ax, pval_dict, y_data_max):
    """Draw brackets only for PAIRS_TO_SHOW that are significant. pval_dict stores log10(p)."""
    idx = {t: i for i, t in enumerate(TREATMENT_ORDER)}
    seen = set()
    sig_pairs = []
    for (g1, g2), lp in pval_dict.items():
        key = tuple(sorted([g1, g2]))
        if key in seen:
            continue
        seen.add(key)
        # Only draw if in the approved list AND significant
        if key in PAIRS_TO_SHOW and not pd.isna(lp) and lp < LOG10_005:
            sig_pairs.append((key[0], key[1], lp))
    sig_pairs.sort(key=lambda c: abs(idx[c[1]] - idx[c[0]]))
    y_start = y_data_max * 1.15
    y_step  = y_data_max * 0.14
    for i, (g1, g2, lp) in enumerate(sig_pairs):
        draw_bracket(ax, idx[g1], idx[g2],
                     y_start + i * y_step, fmt_pval(lp), y_data_max)


def set_xaxis_labels(ax):
    ax.set_xticks(np.arange(len(TREATMENT_ORDER)))
    ax.set_xticklabels([])
    for row_idx, (row_label, row_vals) in enumerate(
            zip(["Ibuprofen", "Carnitine"], [XAXIS_IBUPROFEN, XAXIS_CARNITINE])):
        y_ax = -0.09 - row_idx * 0.075
        ax.text(-0.5, y_ax, row_label, transform=ax.get_xaxis_transform(),
                ha="right", va="center", fontsize=9, style="italic", color="#333333")
        for col_idx, val in enumerate(row_vals):
            ax.text(col_idx, y_ax, val, transform=ax.get_xaxis_transform(),
                    ha="center", va="center", fontsize=10, color="black",
                    fontweight="bold" if val == "+" else "normal")
    ax.axhline(y=0, color="black", linewidth=0.5, clip_on=False)
    ax.text(1.0, -0.27, "Uninjured", transform=ax.get_xaxis_transform(),
            ha="center", va="top", fontsize=10, color="#6B4FA0", fontweight="bold")
    ax.text(4.0, -0.27, "SBI (injured)", transform=ax.get_xaxis_transform(),
            ha="center", va="top", fontsize=10, color="#6B4FA0", fontweight="bold")


def add_background(ax):
    ax.axvspan(-0.5, 2.5, color=BG_UNINJ, zorder=0)
    ax.axvspan(2.5,  5.5, color=BG_SBI,   zorder=0)


# ══════════════════════════════════════════════════════════════════════════════
# 1. LOAD & PARSE DATA
# ══════════════════════════════════════════════════════════════════════════════

print("Loading data...")
raw = pd.read_csv(INPUT_FILE)
raw["Image"] = raw["Image"].astype(str)

parsed = raw["Image"].apply(
    lambda x: pd.Series(parse_image_filename(x),
                        index=["mouse_ID", "treatment_abbrev", "image_number"])
)
raw = pd.concat([raw, parsed], axis=1)
raw["group"] = raw["treatment_abbrev"].map(TREATMENT_MAP)

unmapped = raw["group"].isna().sum()
if unmapped:
    print(f"Warning: {unmapped} rows unmapped and dropped.")
    print(raw.loc[raw["group"].isna(), "treatment_abbrev"].unique())

fibers = raw.dropna(subset=["group"]).copy()
fibers["CSA"] = fibers["Area um^2"]
print(f"Loaded {len(fibers):,} fibers across {fibers['mouse_ID'].nunique()} mice.")

per_mouse = (fibers.groupby(["mouse_ID", "group"])["CSA"]
             .agg(median="median", mean="mean", n="count")
             .reset_index())

# ══════════════════════════════════════════════════════════════════════════════
# 2. KRUSKAL-WALLIS OMNIBUS TEST
# ══════════════════════════════════════════════════════════════════════════════

group_arrays = [fibers.loc[fibers["group"] == t, "CSA"].values for t in TREATMENT_ORDER]

kw_stat, kw_p = kruskal(*group_arrays)
print(f"\nKruskal-Wallis: H = {kw_stat:.3f}, p = {kw_p:.4e}")

# ══════════════════════════════════════════════════════════════════════════════
# 3. DUNN'S POST-HOC
#    p-values stored as log10(p) throughout to avoid underflow
# ══════════════════════════════════════════════════════════════════════════════

all_data   = fibers["CSA"].values
all_groups = fibers["group"].values

ranks   = pd.Series(all_data).rank(method="average").values
n_total = len(ranks)

_, tie_counts  = np.unique(all_data, return_counts=True)
tie_correction = np.sum(tie_counts**3 - tie_counts) / (12 * (n_total - 1))

rows = []
for g1, g2 in combinations(TREATMENT_ORDER, 2):
    mask1 = all_groups == g1
    mask2 = all_groups == g2
    n1, n2 = mask1.sum(), mask2.sum()
    r1, r2 = ranks[mask1].mean(), ranks[mask2].mean()
    se     = np.sqrt((n_total * (n_total + 1) / 12 - tie_correction) * (1/n1 + 1/n2))
    z_stat = (r1 - r2) / se
    # logsf gives log(survival function) = log(1 - CDF), exact even for large |z|
    # two-tailed: log(2) + logsf(|z|), convert to log10
    log10_p_raw = (np.log(2) + scipy_norm.logsf(abs(z_stat))) / np.log(10)
    rows.append({"group1": g1, "group2": g2, "z": z_stat, "log10_p_raw": log10_p_raw})

dunn_df = pd.DataFrame(rows)
n_pairs = len(dunn_df)

# Bonferroni on log scale: log10(p_bonf) = log10(p_raw * n) = log10(p_raw) + log10(n)
# Cap at 0 (i.e. p=1.0)
dunn_df["log10_p_bonf"] = np.minimum(
    dunn_df["log10_p_raw"] + np.log10(n_pairs), 0.0)

dunn_df = dunn_df.sort_values("log10_p_raw").reset_index(drop=True)

print(f"\nDunn's post-hoc ({n_pairs} pairs), sorted by p:")
print(f"  {'Group 1':<35} {'Group 2':<35} {'z':>8}  {'raw p':>18}  {'Bonf p':>18}")
print(f"  {'-'*35} {'-'*35} {'-'*8}  {'-'*18}  {'-'*18}")
for _, row in dunn_df.iterrows():
    print(f"  {row['group1']:<35} {row['group2']:<35} "
          f"{row['z']:+8.3f}  "
          f"{fmt_pval(row['log10_p_raw']):>18}  "
          f"{fmt_pval(row['log10_p_bonf']):>18}")

# Build lookup dicts (values are log10 p)
dunn_pvals_raw  = {}
dunn_pvals_bonf = {}
for _, row in dunn_df.iterrows():
    key = (row["group1"], row["group2"])
    rev = (row["group2"], row["group1"])
    dunn_pvals_raw[key]  = dunn_pvals_raw[rev]  = row["log10_p_raw"]
    dunn_pvals_bonf[key] = dunn_pvals_bonf[rev] = row["log10_p_bonf"]

print("\nSignificant pairs — raw p-values:")
for (g1, g2), lp in sorted(dunn_pvals_raw.items()):
    if g1 < g2 and lp < LOG10_005:
        print(f"  {g1} vs {g2}: {fmt_pval(lp)}")

print("\nSignificant pairs — Bonferroni-adjusted p-values:")
found = False
for (g1, g2), lp in sorted(dunn_pvals_bonf.items()):
    if g1 < g2 and lp < LOG10_005:
        print(f"  {g1} vs {g2}: {fmt_pval(lp)}")
        found = True
if not found:
    print("  None")

# ══════════════════════════════════════════════════════════════════════════════
# 4. VIOLIN PLOT FUNCTION
# ══════════════════════════════════════════════════════════════════════════════

positions  = np.arange(len(TREATMENT_ORDER))
y_data_max = fibers["CSA"].quantile(0.999)


def y_max_for(pval_dict):
    seen = set()
    n_sig = 0
    for (g1, g2), lp in pval_dict.items():
        key = tuple(sorted([g1, g2]))
        if key in seen:
            continue
        seen.add(key)
        if key in PAIRS_TO_SHOW and not pd.isna(lp) and lp < LOG10_005:
            n_sig += 1
    return y_data_max * 1.15 + max(n_sig, 1) * y_data_max * 0.14 + y_data_max * 0.15


def make_violin(pval_dict, title):
    Y_MAX = y_max_for(pval_dict)
    fig, ax = plt.subplots(figsize=(10, 7))
    fig.subplots_adjust(bottom=0.22)
    add_background(ax)

    parts = ax.violinplot(group_arrays, positions=positions,
                          showmedians=False, showextrema=False, widths=0.62)
    for pc, t in zip(parts["bodies"], TREATMENT_ORDER):
        pc.set_facecolor(DOT_COLORS[t])
        pc.set_alpha(0.65)
        pc.set_edgecolor("none")
        pc.set_zorder(2)

    for i, arr in enumerate(group_arrays):
        ax.hlines(np.median(arr), positions[i] - 0.26, positions[i] + 0.26,
                  color="black", linewidth=2.0, zorder=4)

    from scipy.stats import gaussian_kde
    rng2 = np.random.default_rng(RANDOM_SEED)

    # Individual fiber dots — all fibers, jitter shaped to match violin KDE
    for i, t in enumerate(TREATMENT_ORDER):
        arr = fibers.loc[fibers["group"] == t, "CSA"].values
        kde         = gaussian_kde(arr)
        density     = kde(arr)
        max_density = density.max()
        # Jitter width proportional to local density, matching violin shape
        half_width  = 0.38 * (density / max_density)
        jit = rng2.uniform(-1, 1, size=len(arr)) * half_width
        ax.scatter(positions[i] + jit, arr,
                   color=DOT_COLORS[t], alpha=0.15, s=3,
                   linewidths=0, zorder=3)

    # Per-mouse median dots (on top)
    for i, t in enumerate(TREATMENT_ORDER):
        meds = per_mouse.loc[per_mouse["group"] == t, "median"].values
        jit  = rng2.uniform(-0.08, 0.08, size=len(meds))
        ax.scatter(positions[i] + jit, meds, s=72, color="white",
                   edgecolors="black", linewidths=1.4, zorder=5)

    add_brackets(ax, pval_dict, y_data_max)
    set_xaxis_labels(ax)

    ax.set_ylabel("Fiber CSA (µm²)", fontsize=11)
    ax.set_xlim(-0.5, 5.5)
    ax.set_ylim(0, Y_MAX)
    ax.spines[["top", "right", "bottom"]].set_visible(False)
    ax.tick_params(axis="x", length=0)
    ax.legend(handles=[
        mpatches.Patch(facecolor="#888780", alpha=0.75, label="No drug"),
        mpatches.Patch(facecolor="#6B4FA0", alpha=0.75, label="+ Ibuprofen"),
        mpatches.Patch(facecolor="#D85A30", alpha=0.75, label="+ Ibu + Carnitine"),
        Line2D([0], [0], marker="o", color="w", markerfacecolor="#888",
               alpha=0.5, markersize=5, label="Individual fiber (300/group)"),
        Line2D([0], [0], color="black", linewidth=2, label="Group median"),
        Line2D([0], [0], marker="o", color="w", markerfacecolor="white",
               markeredgecolor="black", markersize=8, label="Per-mouse median"),
    ], frameon=False, fontsize=8, loc="upper right")
    ax.set_title(title, fontsize=12, pad=8)
    return fig


# ══════════════════════════════════════════════════════════════════════════════
# 5. STACKED BAR SETUP
# ══════════════════════════════════════════════════════════════════════════════

fibers["csa_bin"] = pd.cut(fibers["CSA"], bins=BIN_EDGES, labels=BIN_LABELS, right=True)
bin_counts = (fibers.groupby(["group", "csa_bin"], observed=True)
              .size().unstack(fill_value=0).reindex(TREATMENT_ORDER))
bin_props  = bin_counts.div(bin_counts.sum(axis=1), axis=0) * 100


def make_stackedbar(title):
    fig, ax = plt.subplots(figsize=(10, 6))
    fig.subplots_adjust(bottom=0.22)
    ax.axvspan(-0.5, 2.5, color=BG_UNINJ, zorder=0)
    ax.axvspan(2.5,  5.5, color=BG_SBI,   zorder=0)
    bottom = np.zeros(len(TREATMENT_ORDER))
    for bl, col in zip(BIN_LABELS, BIN_COLORS):
        vals = bin_props[bl].values
        ax.bar(positions, vals, bottom=bottom, color=col, label=bl,
               width=0.6, edgecolor="white", linewidth=0.5, zorder=2)
        bottom += vals
    set_xaxis_labels(ax)
    ax.set_ylabel("% of fibers", fontsize=11)
    ax.set_ylim(0, 100)
    ax.set_xlim(-0.5, 5.5)
    ax.spines[["top", "right", "bottom"]].set_visible(False)
    ax.tick_params(axis="x", length=0)
    ax.legend(title="CSA bin (µm²)", bbox_to_anchor=(1.01, 1),
              loc="upper left", fontsize=8, frameon=False)
    ax.set_title(title, fontsize=12, pad=8)
    return fig


# ══════════════════════════════════════════════════════════════════════════════
# 6. SAVE FIGURES
# ══════════════════════════════════════════════════════════════════════════════

for pval_dict, stem, p_label in [
    (dunn_pvals_raw,  "fig_violin_kw_raw",
     f"Kruskal-Wallis + Dunn's, raw p-values\n(H={kw_stat:.2f}, p={kw_p:.2e})"),
    (dunn_pvals_bonf, "fig_violin_kw_bonf",
     f"Kruskal-Wallis + Dunn's, Bonferroni-adjusted p-values (n={n_pairs})\n"
     f"(H={kw_stat:.2f}, p={kw_p:.2e})"),
]:
    for fmt in ("png", "pdf"):
        fig = make_violin(pval_dict, p_label)
        fname = f"{stem}.{fmt}"
        kwargs = {"bbox_inches": "tight"}
        if fmt == "png":
            kwargs["dpi"] = 300
        else:
            kwargs["format"] = "pdf"
        fig.savefig(fname, **kwargs)
        plt.close(fig)
        print(f"Saved {fname}")

# Stacked bar (no p-values — descriptive only)
for fmt in ("png", "pdf"):
    fig = make_stackedbar("Fiber CSA distribution")
    fname = f"fig_stackedbar.{fmt}"
    kwargs = {"bbox_inches": "tight"}
    if fmt == "png":
        kwargs["dpi"] = 300
    else:
        kwargs["format"] = "pdf"
    fig.savefig(fname, **kwargs)
    plt.close(fig)
    print(f"Saved {fname}")

print("\nAll done.")